"""Added is_locked column in Auth table

Revision ID: 1d4a925f2e52
Revises: 2ffc2f87215c
Create Date: 2025-08-06 10:56:22.058934

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1d4a925f2e52'
down_revision = '2ffc2f87215c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('auth', 'is_locked')
    # ### end Alembic commands ###
