"""Added description column in Auth table

Revision ID: 7a7f45e6a85f
Revises: 1d4a925f2e52
Create Date: 2025-08-06 10:59:58.988987

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7a7f45e6a85f'
down_revision = '1d4a925f2e52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'description')
    # ### end Alembic commands ###
