"""Adđed email manager table image manager table

Revision ID: 850256836fa0
Revises: 98de43eb2ce5
Create Date: 2025-08-06 13:49:01.635747

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '850256836fa0'
down_revision = '98de43eb2ce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailmanager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sending_status', sa.Boolean(), nullable=False),
    sa.Column('receiver_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiver_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_sending', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('imageinforastorage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inputImageBase64', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('switchModeFlag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imageinforastorage_id'), 'imageinforastorage', ['id'], unique=True)
    op.alter_column('auth', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_imageinforastorage_id'), table_name='imageinforastorage')
    op.drop_table('imageinforastorage')
    op.drop_table('emailmanager')
    # ### end Alembic commands ###
