"""Added is locked description column in User table

Revision ID: 98de43eb2ce5
Revises: 7a7f45e6a85f
Create Date: 2025-08-06 11:18:27.985867

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '98de43eb2ce5'
down_revision = '7a7f45e6a85f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'description')
    op.drop_column('user', 'is_locked')
    # ### end Alembic commands ###
